### ISSUE TITLE
Add a Tile Entity blacklist

### ISSUE THREAD

**Issue by brisingraerowing** [Phylogeny/SimulatedNights#1]
The ExtraUtils2 Quantum Quarry blows up if it is ticked too fast, such as when this mod simulates. A blacklist for tile entities would help prevent this.

For the time being, I am going to remove this mod.

**Comment by Phylogeny** [comment]
A tile entity blacklist now exists in v1.2.0, and is preloaded with EU2's Quantum Quarry.

**Comment by brisingraerowing** [comment]
AWESOME!
